### ISSUE TITLE
Refactor setTag() and getTag() in Adapter

### ISSUE THREAD

**Issue by ntvinh11586** [ntvinh11586/Flicks#2]
The code below should refactor to become independent with `getHighRatingMovieView()` but it has a problem with setTag and getTag in Adapter: 

`````````
highRatingMovieVH.binding.ivHighRatingCover.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(getContext(), TrailerActivity.class);
                intent.putExtra(EXTRA_ID, getItem(position).getId());
                getContext().startActivity(intent);
            }
        });
````````````
If we use `setTag()`,  it will cause crash
````````````
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.coderschool.vinh.flicks, PID: 32612
                  java.lang.IllegalArgumentException: You must not call setTag() on a view Glide is targeting
                      at com.bumptech.glide.request.target.ViewTarget.getRequest(ViewTarget.java:133)
                      at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:650)
                      at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:697)
                      at com.bumptech.glide.DrawableRequestBuilder.into(DrawableRequestBuilder.java:448)
                      at com.coderschool.vinh.flicks.adapter.MovieAdapter.loadHighImage(MovieAdapter.java:111)
                      at com.coderschool.vinh.flicks.databinding.ItemHighRatingMovieBinding.executeBindings(ItemHighRatingMovieBinding.java:103)
                      at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:355)
                      at android.databinding.ViewDataBinding$6.run(ViewDataBinding.java:172)
                      at android.databinding.ViewDataBinding$7.doFrame(ViewDataBinding.java:238)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                      at android.view.Choreographer.doFrame(Choreographer.java:605)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5441)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
````````````

Resource: 
http://stackoverflow.com/questions/34833627/error-you-must-not-call-settag-on-a-view-glide-is-targeting-when-use-glide/35096552#35096552

**Comment by ntvinh11586** [comment]
Fix them by designing new `setTagId()`. 
Alternative way is that we can use `Data-binding` method  (http://developer.android.com/intl/ru/tools/data-binding/guide.html) with `setTag()` from it
Some reference in here: 
https://github.com/bumptech/glide/issues/370
http://stackoverflow.com/a/35096552/5557789
